namespace FootballEngine

module GameData =

    let firstNames =
        Map.ofList
            [ "ARG",
              [ "Bautista"
                "Mateo"
                "Enzo"
                "Nahuel"
                "Julian"
                "Franco"
                "Lautaro"
                "Tiago"
                "Geronimo"
                "Facundo"
                "Ignacio"
                "Nicolas"
                "Lucas"
                "Santiago"
                "Tomas"
                "Valentin"
                "Agustin"
                "Marcos"
                "Luis"
                "Julio"
                "Rodrigo"
                "Joaquin"
                "Thiago"
                "Benjamin"
                "Maximo"
                "Santino"
                "Luciano"
                "Emiliano"
                "Gonzalo"
                "Mauricio"
                "Felipe"
                "Alexis"
                "Damian"
                "Ezequiel"
                "Gaston"
                "Cristian"
                "Sebastian"
                "Martin"
                "Maximiliano"
                "Leandro"
                "Guillermo"
                "Pablo"
                "Fernando"
                "Andres"
                "Diego"
                "Mariano"
                "Adrian"
                "Claudio"
                "Gabriel"
                "Ezequiel"
                "Ramiro"
                "Matias"
                "Ivan"
                "Oscar"
                "Raul"
                "Bruno"
                "Alan"
                "Dylan"
                "Kevin"
                "Brian"
                "Emanuel"
                "Axel"
                "Mathias"
                "Joel"
                "Aaron"
                "Elias"
                "Ian"
                "Liam"
                "Gael"
                "Leon"
                "Noah"
                "Dante"
                "Milo"
                "Benicio"
                "Oliver"
                "Lorenzo"
                "Emilio"
                "Vicente"
                "Bruno"
                "Felipe"
                "Simon"
                "Samuel"
                "Alejo"
                "Lisandro"
                "Jeronimo"
                "Octavio"
                "Renato"
                "Atlas"
                "Gino"
                "Dante"
                "Iker"
                "Rafael"
                "Ismael"
                "Camilo"
                "Matias"
                "Tadeo"
                "Luca"
                "Adriel"
                "Aron"
                "Uriel"
                "Gael"
                "Emir"
                "Izan"
                "Karim" ]
              "BRA",
              [ "Gabriel"
                "Lucas"
                "Matheus"
                "Thiago"
                "Vinicius"
                "Felipe"
                "Guilherme"
                "Joao"
                "Caua"
                "Arthur"
                "Vitor"
                "Igor"
                "Douglas"
                "Bruno"
                "Rodrigo"
                "Ricardo"
                "Murilo"
                "Endrick" ]
              "ENG",
              [ "Harry"
                "Jack"
                "George"
                "Charlie"
                "James"
                "Thomas"
                "Oliver"
                "William"
                "Noah"
                "Jude"
                "Mason"
                "Declan"
                "Ben"
                "Luke"
                "Marcus"
                "Harvey"
                "Cole"
                "Kyle" ]
              "ESP",
              [ "Alvaro"
                "Diego"
                "Iker"
                "Javier"
                "Pablo"
                "Sergio"
                "Adrian"
                "Borja"
                "Hugo"
                "Pau"
                "Ferran"
                "Lamine"
                "Gavi"
                "Dani"
                "Mikel"
                "Nico"
                "Alex"
                "Yeray" ] ]

    let lastNames =
        Map.ofList
            [ "ARG",
              [ "Martinez"
                "Rodriguez"
                "Gomez"
                "Fernandez"
                "Lopez"
                "Diaz"
                "Perez"
                "Romero"
                "Sosa"
                "Alvarez"
                "Torres"
                "García"
                "Acosta"
                "Benítez"
                "Medina"
                "Vázquez"
                "Blanco"
                "Cano" ]
              "BRA",
              [ "Silva"
                "Santos"
                "Oliveira"
                "Souza"
                "Pereira"
                "Alves"
                "Ferreira"
                "Ribeiro"
                "Gomes"
                "Barbosa"
                "Martins"
                "Rocha"
                "Carvalho"
                "Mendes"
                "Soares"
                "Cardoso"
                "Teixeira" ]
              "ENG",
              [ "Smith"
                "Jones"
                "Williams"
                "Brown"
                "Taylor"
                "Davies"
                "Wilson"
                "Evans"
                "Thomas"
                "Johnson"
                "Walker"
                "Alexander"
                "Rice"
                "Foden"
                "Palmer"
                "Saka"
                "Kane"
                "Bellingham" ]
              "ESP",
              [ "Garcia"
                "Rodriguez"
                "Gonzalez"
                "Fernandez"
                "Lopez"
                "Sanchez"
                "Perez"
                "Gomez"
                "Martin"
                "Ruiz"
                "Hernandez"
                "Torres"
                "Navarro"
                "Marin"
                "Vazquez"
                "Ramos"
                "Gil"
                "Serrano" ] ]


    let teamsByCountry =
        Map.ofList
            [ "ENG",
              [

                [ "Man City"
                  "Arsenal"
                  "Liverpool"
                  "Aston Villa"
                  "Tottenham"
                  "Chelsea"
                  "Newcastle"
                  "Man Utd"
                  "West Ham"
                  "Brighton"
                  "Bournemouth"
                  "Wolves"
                  "Fulham"
                  "Crystal Palace"
                  "Everton"
                  "Brentford"
                  "Nottm Forest"
                  "Leicester"
                  "Ipswich"
                  "Southampton" ]

                [ "Burnley"
                  "Luton"
                  "Sheffield Utd"
                  "Leeds"
                  "West Brom"
                  "Norwich"
                  "Hull City"
                  "Middlesbrough"
                  "Coventry"
                  "Preston"
                  "Bristol City"
                  "Cardiff"
                  "Swansea"
                  "Watford"
                  "Sunderland"
                  "Millwall"
                  "QPR"
                  "Stoke City"
                  "Blackburn"
                  "Portsmouth"
                  "Derby County"
                  "Oxford Utd" ] ]
              "ARG",
              [

                [ "River Plate"
                  "Boca Juniors"
                  "Racing Club"
                  "Independiente"
                  "San Lorenzo"
                  "Talleres"
                  "Estudiantes LP"
                  "Defensa y Justicia"
                  "Lanus"
                  "Newell's"
                  "Rosario Central"
                  "Argentinos Jrs"
                  "Huracan"
                  "Godoy Cruz"
                  "Belgrano"
                  "Union SF"
                  "Platense"
                  "Velez Sarsfield"
                  "Instituto"
                  "Banfield"
                  "Gimnasia LP"
                  "Barracas Central"
                  "Tigre"
                  "Atl. Tucuman"
                  "Sarmiento"
                  "Ind. Rivadavia"
                  "Dep. Riestra"
                  "Central Cordoba" ]

                [ "Quilmes"
                  "Ferro"
                  "Chacarita"
                  "Colon"
                  "San Martin T"
                  "San Martin SJ"
                  "Nueva Chicago"
                  "All Boys"
                  "Aldosivi"
                  "Atlanta"
                  "Almagro"
                  "Temperley"
                  "Gimnasia M"
                  "Def. de Belgrano"
                  "Almirante Brown"
                  "Dep. Moron"
                  "Chaco For Ever"
                  "Rafaela" ] ]
              "ESP",
              [

                [ "Real Madrid"
                  "Barcelona"
                  "Atletico Madrid"
                  "Girona"
                  "Athletic Club"
                  "Real Sociedad"
                  "Real Betis"
                  "Valencia"
                  "Villarreal"
                  "Getafe"
                  "Las Palmas"
                  "Osasuna"
                  "Alaves"
                  "Sevilla"
                  "Mallorca"
                  "Rayo Vallecano"
                  "Celta Vigo"
                  "Leganes"
                  "Valladolid"
                  "Espanyol" ]

                [ "Cadiz"
                  "Almeria"
                  "Granada"
                  "Eibar"
                  "Sporting Gijon"
                  "Real Oviedo"
                  "Elche"
                  "Levante"
                  "Burgos"
                  "Racing Santander"
                  "Tenerife"
                  "Albacete"
                  "Cartagena"
                  "Zaragoza"
                  "Huesca"
                  "Mirandes"
                  "Castellon"
                  "Deportivo"
                  "Malaga"
                  "Cordoba" ] ]
              "BRA",
              [

                [ "Palmeiras"
                  "Flamengo"
                  "Botafogo"
                  "Atletico Mineiro"
                  "Sao Paulo"
                  "Gremio"
                  "Internacional"
                  "Fluminense"
                  "Red Bull Bragantino"
                  "Athletico Paranaense"
                  "Fortaleza"
                  "Cuiaba"
                  "Corinthians"
                  "Cruzeiro"
                  "Vasco da Gama"
                  "Bahia"
                  "Vitoria"
                  "Juventude"
                  "Atletico Goianiense"
                  "Criciuma" ]

                [ "Santos"
                  "America Mineiro"
                  "Coritiba"
                  "Goias"
                  "Sport Recife"
                  "Ceara"
                  "Vila Nova"
                  "Mirassol"
                  "Novorizontino"
                  "Avai"
                  "Ponte Preta"
                  "Botafogo-SP"
                  "Ituano"
                  "Brusque"
                  "Paysandu"
                  "Guarani"
                  "Chapecoense"
                  "CRB" ] ] ]


    let leagueNames =
        Map.ofList
            [ "ENG", [ "Premier League"; "Championship" ]
              "ARG", [ "Liga Profesional"; "Primera Nacional" ]
              "ESP", [ "LaLiga"; "LaLiga Hypermotion" ]
              "BRA", [ "Série A"; "Série B" ] ]
